### ISSUE TITLE
[BUG] Cannot connect to windows devices

### ISSUE THREAD

**Issue by trwy7** [moseoridev/WarpShare#19]
**Describe the bug**
I cannot connect to a Windows device

**To Reproduce**
1. Click on a Windows device in the app
2. Select an image
3. App crashes

**Expected behavior**
It should send the file with nearby share 

**Smartphone (please complete the following information):**
 - Device: Pixel 6
 - OS: Android 14 Beta
 - Version 

**Additional context**

**Comment by The-Linux-User** [comment]
AFAIK this App uses the Airdrop protocol to share files from your phone to your Mac. It is not compatible with Windows

**Comment by trwy7** [comment]
I will close this, but why does my windows device show (and with its own windows icon)
