### ISSUE TITLE
[Feature Request] Dark Theme Support

### ISSUE THREAD

**Issue by metezd** [moseoridev/WarpShare#2]
As the title says

**Comment by moseoridev** [comment]
I will definitely add a dark mode, but please understand that it's a bit lower on my priority list right now as I'm focused on stabilizing the behavior of the app.

**Comment by moseoridev** [comment]
I found a workaround that was easier than I thought.
A better design will be introduced with a full UI overhaul.

**Comment by metezd** [comment]
Thanks for saving my eyes!
